<script setup lang="ts">
import { usePersonQuery } from '@/generated/operations' // generated by @nuxt3/graphql-codegen-module
const { result: server, loading: jumpLoading, error } = await usePersonQuery({
  personInput: {
    name: 'Phil Xu',
  },
}, {
  prefetch: true, // ssrMode, default: true
})

</script>

<template>
  <div>
    <div v-if="server && server.person">
      {{ $t('ssrMode') }}: {{ server.person }}
    </div>
  </div>
</template>
